version: '3.2'

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    restart: unless-stopped
    container_name: changedetection
    hostname: changedetection
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      # Routers
      - "traefik.http.routers.changedetect.rule=Host(`${CHANGEDETECT_DOMAIN}`)"
      - "traefik.http.routers.changedetect.tls=true"

      - "traefik.http.services.changedetect.loadbalancer.server.port=5000"
      - "traefik.http.routers.changedetect.entrypoints=web,websecure"

      - "traefik.docker.network=traefik-proxy"
    environment:
      - HIDE_REFERER=true
    volumes:
      - /opt/changedetection/data:/datastore
    networks:
      - "traefik-proxy"

networks:
  traefik-proxy:
    external: true
