---
services:
  ladder:
    image: v2fly/v2fly-core
    container_name: ladder
    networks:
      - "traefik-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ladder.rule=Host(`${LADDER_DOMAIN}`) && PATH(`${LADDER_PATH}`)"
      - "traefik.http.routers.ladder.tls=true"
      - "traefik.http.services.ladder.loadbalancer.server.port=10000"
      - "traefik.http.routers.ladder.entrypoints=web,websecure"

      - "traefik.http.routers.ladder2.rule=Host(`${LADDER_DOMAIN_2}`) && PATH(`${LADDER_PATH_2}`)"
      - "traefik.http.routers.ladder.entrypoints=web,websecure"
      - "traefik.http.routers.ladder2.tls=true"
      - "traefik.http.routers.ladder2.service=ladder@docker"

      - "traefik.docker.network=traefik-proxy"
    command: run -c /etc/v2ray/config.json
    volumes:
      - ${V2RAY_CONFIG_PATH}:/etc/v2ray:ro
      - ${V2RAY_LOG_PATH}:/var/log/v2ray


networks:
  traefik-proxy:
    external: true
...
